name: update s3 bucket

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Customer Env to upgrade'
        required: true
        type: choice
        options:
          - 'dev'
          - 'staging'
          - 'ankit'
      image_tag:
        description: 'Docker image tag to upgrade ex: 0.9.0-8eb15e1-20240814111632'
        required: true

jobs:
  Update-s3-config:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

    - name: Setup jq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Update S3 metadata
      env: 
        BUCKET: "docs.singulr.ai"
        ENV: ${{ github.event.inputs.environment }}
        KEY: "Customer_details/${{ github.event.inputs.environment }}.json"
        IMAGE_TAG: ${{ github.event.inputs.image_tag }}
      run: | 
        echo "Checking if file exists..."
        if ! aws s3api head-object --bucket "$BUCKET" --key "$KEY" >/dev/null 2>&1; then
          echo "File $KEY does not exist. Creating new file..."
          echo '{"CUSTOMER": "'"$ENV"'", "IMAGE_ID": "'"$IMAGE_TAG"'"}' | aws s3 cp - s3://$BUCKET/$KEY
          echo "Created new customer file with initial metadata"
        else
          echo "Fetching existing metadata..."
          metadata=$(aws s3api head-object \
            --bucket "$BUCKET" \
            --key "$KEY" \
            --query Metadata \
            --output json 2>/dev/null || echo '{}')
          echo "Current metadata: $metadata"
          echo "Updating image tag..."
          updated=$(echo "$metadata" | jq --arg tag "$IMAGE_TAG" '.IMAGE_ID=$tag')
          meta_string=$(echo "$updated" | jq -r 'to_entries | map("\(.key)=\(.value)") | join(",")')
          echo "Final metadata: $meta_string"
          aws s3 cp \
            s3://$BUCKET/$KEY \
            s3://$BUCKET/$KEY \
            --metadata "$meta_string" \
            --metadata-directive REPLACE
        fi
