name: update s3 bucket

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Customer Env to upgrade'
        required: true
        type: choice
        options:
          - 'dev'
          - 'staging'
          - 'ankit'
      image_tag:
        description: 'Docker image tag to upgrade ex: 0.9.0-8eb15e1-20240814111632'
        required: true

jobs:
  Update-s3-config:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

    - name: Setup jq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Update S3 JSON config
      env:
        BUCKET: "docs.singulr.ai"
        ENV: ${{ github.event.inputs.environment }}
        KEY: "Customer_details/${{ github.event.inputs.environment }}.json"
        IMAGE_TAG: ${{ github.event.inputs.image_tag }}
      run: |
        set -euo pipefail
        LOCAL_FILE="config.json"

        echo "Checking if file exists in S3..."

        if aws s3api head-object --bucket "$BUCKET" --key "$KEY" >/dev/null 2>&1; then
        echo "File exists → downloading"
        aws s3 cp s3://$BUCKET/$KEY $LOCAL_FILE
        else
        echo "File does not exist → creating new JSON"
        echo '{}' > $LOCAL_FILE
        fi

        echo "Updating JSON..."

        updated=$(jq 
        --arg env "$ENV" 
        --arg tag "$IMAGE_TAG" 
        '
        .CUSTOMER = ($env // .CUSTOMER) |
        .IMAGE_ID = $tag
        ' 
        $LOCAL_FILE)

        echo "$updated" > $LOCAL_FILE

        echo "Final JSON:"
        cat $LOCAL_FILE

        echo "Uploading back to S3..."
        aws s3 cp $LOCAL_FILE s3://$BUCKET/$KEY

        echo "✅ Done"
